# Generated by Django 5.0.3 on 2024-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/no_foto.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
