# Generated by Django 5.0.3 on 2024-05-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wins',
        ),
    ]
