# Generated by Django 5.0.3 on 2024-05-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='game_wins',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
