version: '3.10'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sphere_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345


  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=Sphere.settings

  react:
    build: messaging-ui
    ports:
      - "3000:80"
    depends_on:
      - web
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - react
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./build:/usr/share/nginx/html


  celerybeat:
    build: .
    command: celery -A Sphere beat -l info
    volumes:
      - .:/app
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
