# Generated by Django 5.0.3 on 2024-05-12 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_state', models.CharField(default='         ', max_length=9)),
                ('current_turn', models.CharField(choices=[('X', 'X'), ('O', 'O')], default='X', max_length=1)),
                ('winner', models.CharField(choices=[('X', 'X'), ('O', 'O'), ('', 'None')], default='', max_length=1)),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_x', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
